{{- if .Values.create.faas -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-event-dispatcher
  labels:
    app: {{ template "name" . }}
    component: event-dispatcher
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: event-dispatcher
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-event-dispatcher
          image: "sk8s/event-dispatcher:<%= ENV.fetch('SK8S_IMAGE_TAG') %>"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
          env:
          - name: SERVER_PORT
            value: '8080'
          - name: JAVA_TOOL_OPTIONS
            value: '-Xmx512m'
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
            value: {{ template "fullname" . }}-kafka:9092
          - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
            value: {{ template "fullname" . }}-zookeeper:2181
          - name: SK8S_FUNCTION_CONTROLLER_SIDECAR_TAG
            value: <%= ENV.fetch('SIDECAR_IMAGE_TAG') %>
{{- end -}}
