apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: tweets
---

apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: sentiments
---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: sentiments
spec:
  protocol: stdio
  input: tweets
  output: sentiments
  container:
    image: projectriff/sentiments:v0001
