---
apiVersion: projectriff.io/v1alpha1
kind: Binding
metadata:
  name: matching-invoker-with-output-topic
spec:
  handler: matching-invoker-with-output-topic
  input: matching-invoker-with-output-topic
  output: soundReflection
