language: go
go:
  - "1.9"
script: make test
matrix:
  include:
    - stage: test
      before_script: cd function-controller
    - stage: test
      sudo: required
      env:
        - KAFKA_BROKER=localhost:9092
      before_install:
        - ./.travis.install-kafka.sh
      before_script: cd function-sidecar
    - stage: test
      before_script: cd http-gateway
    - stage: test
      sudo: required
      env:
        - KAFKA_BROKERS=localhost:9092
      before_install:
        - ./.travis.install-kafka.sh
      before_script: cd message-transport
    - stage: test
      before_script: cd riff-cli
    - stage: test
      before_script: cd topic-controller
    - stage: publish
      sudo: required
      services:
      - docker
      script: ./.travis.docker-push.sh
stages:
  - test
  - name: publish
    if: branch = master AND type = push