language: go
go:
  - "1.9"
matrix:
  include:
    - stage: test
      script: cd function-controller && make test
    - stage: test
      sudo: required
      env:
        - KAFKA_BROKER=localhost:9092
      before_install:
        - ./.travis.install-kafka.sh
      script: cd function-sidecar && make test
    - stage: test
      script: cd http-gateway && make test
    - stage: test
      sudo: required
      env:
        - KAFKA_BROKERS=localhost:9092
      before_install:
        - ./.travis.install-kafka.sh
      script: cd message-transport && make test
    - stage: test
      script: cd riff-cli && make test verify-docs
    - stage: test
      script: cd topic-controller && make test
    - stage: publish
      sudo: required
      services:
      - docker
      script: ./.travis.docker-push.sh
stages:
  - test
  - name: publish
    if: branch = master AND type = push