# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

trigger:
- master

pool:
  vmImage: $(imageName)

variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/opt/hostedtoolcache/go/1.12.0/x64' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(build.repository.name)' # Path to the module's code

steps:
- task: GoTool@0
  inputs:
    version: 1.12

- bash: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'

    set -o errexit
    set -o nounset
    set -o pipefail

    go get github.com/jstemmer/go-junit-report
    go get github.com/axw/gocov/gocov
    go get github.com/AlekSi/gocov-xml
    go get -u github.com/matm/gocov-html
  displayName: 'Set up the Go workspace'

- bash: |
    set -o errexit
    set -o nounset
    set -o pipefail

    go version

    go build -v ./cmd/riff
    go test -v -coverprofile=coverage.txt -covermode count ./... 2>&1 | tee >(go-junit-report > report.xml)
  # TODO drop this condition once windows tests are passing
  condition: and(succeeded(), nq(variables['Agent.OS'], 'Windows_NT'))
  workingDirectory: '$(modulePath)'
  displayName: 'Run unit test'

# TODO drop this step once windows tests are passing
- bash: |
    set -o errexit
    set -o nounset
    set -o pipefail

    go version

    go build -v ./cmd/riff
    go test -v -coverprofile=coverage.txt -covermode count ./... 2>&1 | tee >(go-junit-report > report.xml)
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
  continueOnError: true
  workingDirectory: '$(modulePath)'
  displayName: 'Run unit test Windows'

- bash: |
    set -o errexit
    set -o nounset
    set -o pipefail

    if [ -f "coverage.txt" ]; then
      gocov convert coverage.txt > coverage.json
      gocov-xml < coverage.json > coverage.xml
      mkdir coverage
      gocov-html < coverage.json > coverage/index.html
    fi
  condition: succeededOrFailed()
  workingDirectory: '$(modulePath)'
  displayName: 'Process test coverage'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml

- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml
    reportDirectory: $(System.DefaultWorkingDirectory)/**/coverage
