{{- if .Values.create.faas -}}
{{- if .Values.enable.metricsDashboard -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-prometheus
  labels:
    app: {{ template "name" . }}
    component: prometheus
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      # Override the global default and scrape targets from this job every 5 seconds.
      scrape_interval: 5s
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'sk8s'
      # Override the global default and scrape targets from this job every 5 seconds.
      scrape_interval: 5s
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      metrics_path: '/prometheus'
      static_configs:
      - targets: ['{{ template "fullname" . }}-http-gateway:{{ .Values.httpGateway.service.externalPort }}','{{ template "fullname" . }}-event-dispatcher:{{ .Values.eventDispatcher.service.externalPort }}']
{{- end -}}
{{- end -}}
