{{- if .Values.create.faas -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-zookeeper
  labels:
    app: {{ template "name" . }}
    component: zookeeper
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.zookeeper.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        component: zookeeper
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-zookeeper
          image: "wurstmeister/zookeeper:3.4.6"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
          - name: ZOOKEEPER_ID
            value: "1"
          - name: ZOOKEEPER_SERVER_1
            value: {{ template "fullname" . }}-zookeeper
{{- end -}}
