# Default values for sk8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
create:
  crd: true
  faas: true
enable:
  metricsDashboard: false
  tracingDashboard: false
eventDispatcher:
  replicaCount: 1
  image:
    repository: sk8s/event-dispatcher
    tag: 0.0.1-SNAPSHOT
    pullPolicy: IfNotPresent
  sidecarImage:
    repository: sk8s/function-sidecar
    name: 0.0.1-SNAPSHOT
  service:
    name: http
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
topicController:
  replicaCount: 1
  image:
    repository: sk8s/topic-controller
    tag: 0.0.1-SNAPSHOT
    pullPolicy: IfNotPresent
topicGateway:
  replicaCount: 1
  image:
    repository: sk8s/topic-gateway
    tag: 0.0.1-SNAPSHOT
    pullPolicy: IfNotPresent
  service:
    name: http
    type: LoadBalancer
    externalPort: 80
    internalPort: 8080
grafana:
  replicaCount: 1
  image:
    repository: grafana/grafana
    tag: 4.4.1
    pullPolicy: IfNotPresent
  service:
    name: graphana
    type: LoadBalancer
    externalPort: 3000
    internalPort: 3000
prometheus:
  replicaCount: 1
  image:
    repository: prom/prometheus
    tag: v1.7.1
    pullPolicy: IfNotPresent
  service:
    name: prometheus
    type: LoadBalancer
    externalPort: 9090
    internalPort: 9090
zipkin:
  replicaCount: 1
  image:
    repository: sk8s/zipkin-server
    tag: 0.0.1-SNAPSHOT
    pullPolicy: IfNotPresent
  service:
    name: zipkin
    type: LoadBalancer
    externalPort: 9411
    internalPort: 9411
zookeeper:
  replicaCount: 1
  image:
    repository: wurstmeister/zookeeper
    tag: 3.4.6
    pullPolicy: IfNotPresent
  service:
    name: zookeeper
    type: ClusterIP
    externalPort: 2181
    internalPort: 2181
kafka:
  replicaCount: 1
  image:
    repository: wurstmeister/kafka
    tag: 0.11.0.1
    pullPolicy: IfNotPresent
  service:
    name: kafka
    type: ClusterIP
    externalPort: 9092
    internalPort: 9092
