# Default values for sk8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
create:
  crd: true
  faas: true
enable:
  metricsDashboard: false
  tracingDashboard: false
eventDispatcher:
  replicaCount: 1
topicController:
  replicaCount: 1
httpGateway:
  replicaCount: 1
  service:
    externalPort: 80
grafana:
  replicaCount: 1
  service:
    externalPort: 3000
prometheus:
  replicaCount: 1
  service:
    externalPort: 9090
zipkin:
  replicaCount: 1
  service:
    externalPort: 9411
zookeeper:
  replicaCount: 1
kafka:
  replicaCount: 1
