---
apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: matching-invoker-invoker-version
spec:
  container:
    image: rifftest/matching-invoker-invoker-version:0.0.1
  input: matching-invoker-invoker-version
  protocol: grpc
