kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: projectriff-riff
subjects:
- kind: ServiceAccount
  name: projectriff-riff
roleRef:
  kind: Role
  name: projectriff-riff
  apiGroup: rbac.authorization.k8s.io
