kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: projectriff-riff
subjects:
- kind: ServiceAccount
  name: projectriff-riff
  namespace: riff-system
roleRef:
  kind: ClusterRole
  name: projectriff-riff
  apiGroup: rbac.authorization.k8s.io
