kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: riff-rb
subjects:
- kind: ServiceAccount
  name: riff-sa
roleRef:
  kind: Role
  name: riff-role
  apiGroup: rbac.authorization.k8s.io
