apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: invokers.projectriff.io
spec:
  scope: Cluster
  group: projectriff.io
  version: v1alpha1
  names:
    kind: Invoker
    plural: invokers
    singular: invoker
