apiVersion: v1
kind: Service
metadata:
  name: projectriff-kafka
  labels:
    app: kafka
    component: kafka-broker
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka
    component: kafka-broker

---
apiVersion: v1
kind: Service
metadata:
  name: projectriff-zookeeper
  labels:
    app: kafka
    component: zookeeper
spec:
  ports:
  - port: 2181
    name: zookeeper-port
    targetPort: 2181
    protocol: TCP
  selector:
    app: kafka
    component: zookeeper

---
apiVersion: v1
kind: Service
metadata:
  name: projectriff-brokers
  labels:
    app: kafka
    component: kafka-broker
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: broker # Port is not used
  selector:
    app: kafka
    component: kafka-broker

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka
    component: zookeeper
  name: projectriff-zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        component: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:3.4.6
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zookeeper

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka
    component: kafka-broker
  name: projectriff-kafka
spec:
  replicas: 1 # The headless service/hostname config only supports 1 replica!
  template:
    metadata:
      labels:
        app: kafka
        component: kafka-broker
    spec:
      hostname: broker-1
      subdomain: projectriff-brokers
      containers:
      - name: kafka
        image: wurstmeister/kafka:0.11.0.1
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: broker-1.projectriff-brokers.riff-system.svc.cluster.local
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: projectriff-zookeeper:2181
