---
apiVersion: projectriff.io/v1alpha1
kind: Function
metadata:
  name: matching-invoker-handler
spec:
  container:
    image: rifftest/matching-invoker-handler:0.0.1
  input: matching-invoker-handler
  protocol: grpc
