apiVersion: extensions.sk8s.io/v1
kind: Function
metadata:
  name: echo
spec:
  input: greetings
  protocol: stdio
  image: busybox
  command: ["/bin/sh", "-c"]
  args: ['while read X; do echo "received: $X"; done</pipes/input >/pipes/output']
