apiVersion: v1
kind: Service
metadata:
  name: sample-functions
  labels:
    app: sample-functions
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: sample-functions
