apiVersion: v1
kind: Service
metadata:
  name: event-dispatcher
  labels:
    app: event-dispatcher
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8080
    nodePort: 30113
  selector:
    app: event-dispatcher
