apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topic-controller
spec:
  replicas: 1
  template:
    metadata:
      name: topic-controller
      labels:
        app: topic-controller
    spec:
      containers:
      - image: sk8s/topic-controller:v0001
        name: topic-controller
        imagePullPolicy: IfNotPresent
        env:
        - name: JAVA_TOOL_OPTIONS
          value: '-Xmx512m'
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: kafka:9092
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
          value: zookeeper:2181
