apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: topic-controller
spec:
  replicas: 1
  template:
    metadata:
      name: topic-controller
      labels:
        app: riff
        component: topic-controller
    spec:
      containers:
      - image: projectriff/topic-controller:0.0.3-snapshot
        name: topic-controller
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: KAFKA_ZK_NODES
          value: zookeeper:2181
      serviceAccountName: riff-sa
