apiVersion: v1
kind: Service
metadata:
  name: topic-controller
  labels:
    app: topic-controller
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8080
    nodePort: 30112
  selector:
    app: topic-controller
