apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: names
---

apiVersion: projectriff.io/v1
kind: Topic
metadata:
  name: greetings
spec:
  partitions: 3

---

apiVersion: projectriff.io/v1
kind: Function
metadata:
  name: wordcount
spec:
  protocol: stdio
  input: names
  output: greetings
  container:
    image: projectriff/wordcount:v0001
